package com.ciap.mc.item;

import com.ciap.mc.food.ModFoodComponents;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.item.Item;
import net.minecraft.item.ToolMaterials;
import net.minecraft.tag.BlockTags;
import net.minecraft.util.registry.Registry;

import static com.ciap.mc.Tier0Mod.getIdentifier;

public class ModItemRegistry {
    public static final Item COAL_COKE = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item COAL_COKE_CHUNKS = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item OIL_PRESS_PISTON = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP).maxCount(1));
    public static final Item PRESS_PISTON = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP).maxCount(1));
    public static final Item OIL_BUCKET = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP).maxCount(1));
    public static final Item IRON_PLATE = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item COPPER_PLATE = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item CRUSHING_WHEEL = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item PYRITE = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item COAL_DUST = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item CRUSHED_POTATO = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item STARCH = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item BIO_PLASTIC = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item ECO_LEATHER = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item SULFUR = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item MACE = new MaceItem(ToolMaterials.IRON, 4, -2.8F, new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item SAW = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item SAW_DUST = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item LIGHT_STICK = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item COPPER_WIRE = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item HARVESTER_HEAD = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item OIL_BOTTLE = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item CRYING_OBSIDIAN_DUST = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item PORTAL_DUST = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item PORTAL_CRYSTAL = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item MIXED_PORTAL_CRYSTAL = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item TELEPORT_WAND = new TeleportWand(new FabricItemSettings().group(ModItemGroup.tier0_GROUP).maxCount(1));
    public static final Item TELEPORT_WAND_WHITE = new TeleportWand(new FabricItemSettings().group(ModItemGroup.tier0_GROUP).maxCount(1));
    public static final Item TELEPORT_WAND_GREEN = new TeleportWand(new FabricItemSettings().group(ModItemGroup.tier0_GROUP).maxCount(1));
    public static final Item TELEPORT_WAND_RED = new TeleportWand(new FabricItemSettings().group(ModItemGroup.tier0_GROUP).maxCount(1));
    public static final Item TELEPORT_WAND_BLUE = new TeleportWand(new FabricItemSettings().group(ModItemGroup.tier0_GROUP).maxCount(1));
    public static final Item TELEPORT_WAND_BLACK = new TeleportWand(new FabricItemSettings().group(ModItemGroup.tier0_GROUP).maxCount(1));
    public static final Item COMPRESSED_REDSTONE = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item URANIUM_SHARD = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item URANIUM_CARROT = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP).food(ModFoodComponents.URANIUM_CARROT));
    public static final Item GREEN_LANTERN = new BatteryItem(new FabricItemSettings().group(ModItemGroup.tier0_GROUP).maxDamage(2000));
    public static final Item URANIUM_DUST = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item FUEL_BRICK = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item FUEL_DUST = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item NETHER_CRYSTAL_SHARD = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item NETHER_CRYSTAL = new Item(new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static final Item HAMMER = new HammerTool( 1, -2.8F, ToolMaterials.DIAMOND, BlockTags.PICKAXE_MINEABLE, new FabricItemSettings().group(ModItemGroup.tier0_GROUP));
    public static void setup() {
        Registry.register(Registry.ITEM, getIdentifier("coal_coke"), COAL_COKE);
        Registry.register(Registry.ITEM, getIdentifier("coal_coke_chunks"), COAL_COKE_CHUNKS);
        Registry.register(Registry.ITEM, getIdentifier("press_piston"), PRESS_PISTON);
        Registry.register(Registry.ITEM, getIdentifier("oil_press_piston"), OIL_PRESS_PISTON);
        Registry.register(Registry.ITEM, getIdentifier("oil_bucket"), OIL_BUCKET);
        Registry.register(Registry.ITEM, getIdentifier("copper_plate"), COPPER_PLATE);
        Registry.register(Registry.ITEM, getIdentifier("iron_plate"), IRON_PLATE);
        Registry.register(Registry.ITEM, getIdentifier("crushing_wheel"), CRUSHING_WHEEL);
        Registry.register(Registry.ITEM, getIdentifier("pyrite"), PYRITE);
        Registry.register(Registry.ITEM, getIdentifier("coal_dust"), COAL_DUST);
        Registry.register(Registry.ITEM, getIdentifier("crushed_potato"), CRUSHED_POTATO);
        Registry.register(Registry.ITEM, getIdentifier("starch"), STARCH);
        Registry.register(Registry.ITEM, getIdentifier("bio_plastic"), BIO_PLASTIC);
        Registry.register(Registry.ITEM, getIdentifier("eco_leather"), ECO_LEATHER);
        Registry.register(Registry.ITEM, getIdentifier("mace"), MACE);
        Registry.register(Registry.ITEM, getIdentifier("sulfur"), SULFUR);
        Registry.register(Registry.ITEM, getIdentifier("saw"), SAW);
        Registry.register(Registry.ITEM, getIdentifier("sawdust"), SAW_DUST);
        Registry.register(Registry.ITEM, getIdentifier("light_stick"), LIGHT_STICK);
        Registry.register(Registry.ITEM, getIdentifier("copper_wire"), COPPER_WIRE);
        Registry.register(Registry.ITEM, getIdentifier("harvester_head"), HARVESTER_HEAD);
        Registry.register(Registry.ITEM, getIdentifier("oil_bottle"), OIL_BOTTLE);
        Registry.register(Registry.ITEM, getIdentifier("crying_obsidian_dust"), CRYING_OBSIDIAN_DUST);
        Registry.register(Registry.ITEM, getIdentifier("portal_dust"), PORTAL_DUST);
        Registry.register(Registry.ITEM, getIdentifier("portal_crystal"), PORTAL_CRYSTAL);
        Registry.register(Registry.ITEM, getIdentifier("mixed_portal_crystal"), MIXED_PORTAL_CRYSTAL);
        Registry.register(Registry.ITEM, getIdentifier("teleport_wand"), TELEPORT_WAND);
        Registry.register(Registry.ITEM, getIdentifier("teleport_wand_white"), TELEPORT_WAND_WHITE);
        Registry.register(Registry.ITEM, getIdentifier("teleport_wand_blue"), TELEPORT_WAND_BLUE);
        Registry.register(Registry.ITEM, getIdentifier("teleport_wand_red"), TELEPORT_WAND_RED);
        Registry.register(Registry.ITEM, getIdentifier("teleport_wand_green"), TELEPORT_WAND_GREEN);
        Registry.register(Registry.ITEM, getIdentifier("teleport_wand_black"), TELEPORT_WAND_BLACK);
        Registry.register(Registry.ITEM, getIdentifier("compressed_redstone"), COMPRESSED_REDSTONE);
        Registry.register(Registry.ITEM, getIdentifier("uranium_shard"), URANIUM_SHARD);
        Registry.register(Registry.ITEM, getIdentifier("uranium_carrot"), URANIUM_CARROT);
        Registry.register(Registry.ITEM, getIdentifier("uranium_dust"), URANIUM_DUST);
        Registry.register(Registry.ITEM, getIdentifier("green_lantern"), GREEN_LANTERN);
        Registry.register(Registry.ITEM, getIdentifier("fuel_brick"), FUEL_BRICK);
        Registry.register(Registry.ITEM, getIdentifier("fuel_dust"), FUEL_DUST);
        Registry.register(Registry.ITEM, getIdentifier("hammer"), HAMMER);
        Registry.register(Registry.ITEM, getIdentifier("nether_crystal_shard"), NETHER_CRYSTAL_SHARD);
        Registry.register(Registry.ITEM, getIdentifier("nether_crystal"), NETHER_CRYSTAL);
    }
}
